name: Docker Nightly

on:
  # This can be used to automatically publish nightlies at UTC nighttime
  schedule:
    - cron: '0 1 * * *' # run at 1 AM UTC
  # This can be used to allow manually triggering nightlies from the web interface
  workflow_dispatch:

jobs:
  check_date:
    if: github.repository_owner == 'McPringle'
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
      - name: print latest_commit
        run: echo ${{ github.sha }}
      - id: should_run
        continue-on-error: true
        if: ${{ github.event_name == 'schedule' }}
        name: check latest commit is less than a day
        run: |
          sha=$(git rev-list --after="5 minutes" ${{ github.sha }})
          if test -z $sha
          then
            echo "should_run=false" >> $GITHUB_OUTPUT
          else
            echo "should_run=true" >> $GITHUB_OUTPUT
          fi
  docker:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    runs-on: ubuntu-latest
    name: Docker Nightly

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Check for changes
        continue-on-error: true
        shell: bash
        run: 'test -n "$(git reflog main --since="24 hours")"'
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: mcpringle/apus:nightly
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: mcpringle/apus
